# Arena related constants
ARENA_WIDTH = 15
ARENA_HEIGHT = 20

ROBOT_START_POINT = [18, 1]
ROBOT_END_POINT = [1, 13]

NORTH_POSITION = (-1, 0)
SOUTH_POSITION = (1, 0)
EAST_POSITION = (0, 1)
WEST_POSITION = (0, -1)

NEIGHBOURING_POSITIONS = [
    NORTH_POSITION, SOUTH_POSITION, EAST_POSITION, WEST_POSITION
]

MOVE_COST = 1
NO_TURN_COST = 0
TURN_COST_PERPENDICULAR = 2
TURN_COST_OPPOSITE_DIRECTION = 4

# Tkinter settings
WINDOW_WIDTH_IN_PIXELS = 1280
WINDOW_HEIGHT_IN_PIXELS = 720

START_GOAL_NODE_COLOUR = 'gold'
OBSTACLE_NODE_COLOUR = 'black'
VIRTUAL_WALL_NODE_COLOUR = 'gray'
WAYPOINT_NODE_COLOUR = 'green'
FREE_AREA_NODE_COLOUR = 'white'
ROBOT_BODY_COLOUR = 'red'
ROBOT_HEADER_COLOUR = 'pink'
