# Tkinter settings
WINDOW_WIDTH_IN_PIXELS = 1280
WINDOW_HEIGHT_IN_PIXELS = 720

START_GOAL_NODE_COLOUR = 'gold'
OBSTACLE_NODE_COLOUR = 'black'
VIRTUAL_WALL_NODE_COLOUR = 'gray'
WAYPOINT_NODE_COLOUR = 'green'
FREE_AREA_NODE_COLOUR = 'white'
ROBOT_BODY_COLOUR = 'red'
ROBOT_HEADER_COLOUR = 'pink'