# Tkinter settings
WINDOW_WIDTH_IN_PIXELS = 1280
WINDOW_HEIGHT_IN_PIXELS = 720

START_GOAL_NODE_COLOUR = '#42a5f5'
OBSTACLE_NODE_COLOUR = '#212121'
VIRTUAL_WALL_NODE_COLOUR = '#bdbdbd'
WAYPOINT_NODE_COLOUR = '#7780a9'
FREE_AREA_NODE_COLOUR = 'white'
ROBOT_BODY_COLOUR = '#344441'
ROBOT_HEADER_COLOUR = 'white'
RECTANGLE_OUTLINE = '#efefef'
